# Generated by Django 6.0 on 2026-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='total_seats',
            new_name='available_ac1_seats',
        ),
        migrations.RemoveField(
            model_name='train',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='train',
            name='available_ac2_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='available_ac3_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='available_sl_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='total_ac1_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='total_ac2_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='total_ac3_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='total_sl_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
