# Generated by Django 6.0 on 2026-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniSystem', '0002_rename_total_seats_train_available_ac1_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC 1 Tier')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
