# Generated by Django 6.0 on 2026-01-06 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniSystem', '0003_booking_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
