# Generated by Django 6.0 on 2026-01-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniSystem', '0004_booking_booked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('available_sl_seats', models.PositiveIntegerField()),
                ('available_ac3_seats', models.PositiveIntegerField()),
                ('available_ac2_seats', models.PositiveIntegerField()),
                ('available_ac1_seats', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='miniSystem.train')),
            ],
            options={
                'unique_together': {('train', 'journey_date')},
            },
        ),
    ]
